name: Sync root content to ichbiofarm.github.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone ichbiofarm.github.io repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://x-access-token:${{ secrets.ICH_TOKEN }}@github.com/ichbiofarm/ichbiofarm.github.io.git out

      - name: Copy root content to target repo (ignore .github etc)
        run: |
          shopt -s extglob
          rm -rf out/*
          cp -r !(out|.git|.github|README.md|LICENSE) out/
          cd out
          git add .
          git commit -m "Auto sync from main-project root - $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
          git push
